# Generated by Django 4.0.6 on 2022-08-08 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ZumaApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='index',
            name='upload',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
